var searchData=
[
  ['randomcentroidstransform',['RandomCentroidsTransform',['../classbr_1_1RandomCentroidsTransform.html',1,'br']]],
  ['rankoutput',['rankOutput',['../classbr_1_1rankOutput.html',1,'br']]],
  ['ranktransform',['RankTransform',['../classbr_1_1RankTransform.html',1,'br']]],
  ['rawformat',['rawFormat',['../classbr_1_1rawFormat.html',1,'br']]],
  ['rectfrompointstransform',['RectFromPointsTransform',['../classbr_1_1RectFromPointsTransform.html',1,'br']]],
  ['rectregionstransform',['RectRegionsTransform',['../classbr_1_1RectRegionsTransform.html',1,'br']]],
  ['recursiveintegralsamplertransform',['RecursiveIntegralSamplerTransform',['../classbr_1_1RecursiveIntegralSamplerTransform.html',1,'br']]],
  ['recursiveproductquantizationdistance',['RecursiveProductQuantizationDistance',['../classbr_1_1RecursiveProductQuantizationDistance.html',1,'br']]],
  ['redlinearregressiontransform',['RedLinearRegressionTransform',['../classbr_1_1RedLinearRegressionTransform.html',1,'br']]],
  ['regexpropertytransform',['RegexPropertyTransform',['../classbr_1_1RegexPropertyTransform.html',1,'br']]],
  ['removetemplatestransform',['RemoveTemplatesTransform',['../classbr_1_1RemoveTemplatesTransform.html',1,'br']]],
  ['removetransform',['RemoveTransform',['../classbr_1_1RemoveTransform.html',1,'br']]],
  ['renamefirsttransform',['RenameFirstTransform',['../classbr_1_1RenameFirstTransform.html',1,'br']]],
  ['renametransform',['RenameTransform',['../classbr_1_1RenameTransform.html',1,'br']]],
  ['reshapetransform',['ReshapeTransform',['../classbr_1_1ReshapeTransform.html',1,'br']]],
  ['resizetransform',['ResizeTransform',['../classbr_1_1ResizeTransform.html',1,'br']]],
  ['resource',['Resource',['../classbr_1_1Resource.html',1,'br']]],
  ['resource_3c_20br_3a_3atransform_20_3e',['Resource&lt; br::Transform &gt;',['../classbr_1_1Resource.html',1,'br']]],
  ['resource_3c_20nt4context_20_3e',['Resource&lt; NT4Context &gt;',['../classbr_1_1Resource.html',1,'br']]],
  ['resourcemaker',['ResourceMaker',['../classbr_1_1ResourceMaker.html',1,'br']]],
  ['resourcemaker_3c_20cascadeclassifier_20_3e',['ResourceMaker&lt; CascadeClassifier &gt;',['../classbr_1_1ResourceMaker.html',1,'br']]],
  ['resourcemaker_3c_20stasmcascadeclassifier_20_3e',['ResourceMaker&lt; StasmCascadeClassifier &gt;',['../classbr_1_1ResourceMaker.html',1,'br']]],
  ['resourcemaker_3c_20transform_20_3e',['ResourceMaker&lt; Transform &gt;',['../classbr_1_1ResourceMaker.html',1,'br']]],
  ['restoremattransform',['RestoreMatTransform',['../classbr_1_1RestoreMatTransform.html',1,'br']]],
  ['resttransform',['RestTransform',['../classbr_1_1RestTransform.html',1,'br']]],
  ['retaintransform',['RetainTransform',['../classbr_1_1RetainTransform.html',1,'br']]],
  ['rgtransform',['RGTransform',['../classbr_1_1RGTransform.html',1,'br']]],
  ['rndpointtransform',['RndPointTransform',['../classbr_1_1RndPointTransform.html',1,'br']]],
  ['rndregiontransform',['RndRegionTransform',['../classbr_1_1RndRegionTransform.html',1,'br']]],
  ['rndsubspacetransform',['RndSubspaceTransform',['../classbr_1_1RndSubspaceTransform.html',1,'br']]],
  ['roifromptstransform',['ROIFromPtsTransform',['../classbr_1_1ROIFromPtsTransform.html',1,'br']]],
  ['roitransform',['ROITransform',['../classbr_1_1ROITransform.html',1,'br']]],
  ['rootnormtransform',['RootNormTransform',['../classbr_1_1RootNormTransform.html',1,'br']]],
  ['rowwisemeancentertransform',['RowWiseMeanCenterTransform',['../classbr_1_1RowWiseMeanCenterTransform.html',1,'br']]],
  ['rowwisepcatransform',['RowWisePCATransform',['../classbr_1_1RowWisePCATransform.html',1,'br']]],
  ['rroutput',['rrOutput',['../classbr_1_1rrOutput.html',1,'br']]]
];
